// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hvntkmjtgxbdqhfyfgpc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh2bnRrbWp0Z3hiZHFoZnlmZ3BjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0MTIyMjksImV4cCI6MjA2OTk4ODIyOX0.fZrB9zYOKyrzpRMQSfJEJVdTgz-EQHZNlPlrp8XRQs8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});